# Permalinks
permalink:           pretty

# Setup
title:               Zhizun Zhang's Blog
tagline:             
url:                 "https://zazhang.github.io"
paginate:            2
baseurl:             "https://zazhang.github.io/blog/" # comment out this line when testing locally at http://localhost:4000

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Albert Zhang
  url:               https://zazhang.github.io
  email:             godzaq159753@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown processors
kramdown:
input: GFM
hard_wrap: false
auto_ids: true
footnote_nr: 1
entity_output: as_char
toc_levels: 1..6
smart_quotes: lsquo,rsquo,ldquo,rdquo
enable_coderay: false

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
